[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  SUPABASE_URL = "YOUR_SUPABASE_URL"
  SUPABASE_SERVICE_KEY = "YOUR_SERVICE_ROLE_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
